<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function buddyxpro_child_enqueue_styles() {
	wp_enqueue_style( 'buddyx-pro-style', get_template_directory_uri() . '/style.css' );
	wp_enqueue_style(
		'buddyx-pro-child-style',
		get_stylesheet_directory_uri() . '/style.css',
		array( 'buddyx-pro-style' ),
		wp_get_theme()->get( 'Version' )
	);
}

add_action( 'wp_enqueue_scripts', 'buddyxpro_child_enqueue_styles' );

if ( get_stylesheet() !== get_template() ) {
	add_filter(
		'pre_update_option_theme_mods_' . get_stylesheet(),
		function ( $value, $old_value ) {
			update_option( 'theme_mods_' . get_template(), $value );
			return $old_value; // prevent update to child theme mods.
		},
		10,
		2
	);
	add_filter(
		'pre_option_theme_mods_' . get_stylesheet(),
		function (
			$default_values
		) {
			return get_option( 'theme_mods_' . get_template(), $default_values );
		}
	);
}

// Gravity Forms Customization for creating The Events Calendar events from the front end
// Reference: https://docs.gravityforms.com/advanced-post-creation-add-on-using-third-party-post-types/#h-populating-drop-down-with-event-categories

add_action( 'gform_advancedpostcreation_post_after_creation', 'update_event_information', 10, 4 );
function update_event_information( $post_id, $feed, $entry, $form ){
    //update the All Day setting
    $all_day = $entry['9.1'];
    if ( $all_day == 'All Day' ){
        update_post_meta( $post_id, '_EventAllDay', 'yes');
    }
  
    //update the Hide From Monthly View Setting
    $hide = $entry['9.2'];
    if ( $hide == 'Hide From Event Listings') {
        update_post_meta( $post_id, '_EventHideFromUpcoming', 'yes' );
    }
  
    //update the Sticky in Month View setting
    $sticky = $entry['9.3'];
    if ( $sticky == 'Sticky in Month View' ){
        wp_update_post(array( 'ID' => $post_id, 'menu_order' => '-1' ) );
    }
    else{
        wp_update_post(array( 'ID' => $post_id, 'menu_order' => '0' ) );
    }
  
    //update the Feature Event setting
    $feature = $entry['9.4'];
    if ( $feature == 'Feature Event'){
        update_post_meta( $post_id, '_tribe_featured', '1');
    }
    else{
        update_post_meta( $post_id, '_tribe_featured', '0');
    }
}



// Sort BuddyPress users by last name
//
// Use this Gist to sort members alphabetically by last name in the
// members directory. Follow the instructions below and drop the code
// in your functions.php or your functions plugin.
//
// Updated to work with BP 1.7. See earlier revisions of this gist for
// earlier versions of BP.

/**
 * Sort users by last name
 *
 * Changes the querystring for the member directory to sort users by their last name
 *
 * @param BP_User_Query $bp_user_query
 */
function alphabetize_by_last_name( $bp_user_query ) {
    if ( 'alphabetical' == $bp_user_query->query_vars['type'] )
        $bp_user_query->uid_clauses['orderby'] = "ORDER BY substring_index(u.display_name, ' ', -1)";
}
add_action ( 'bp_pre_user_query', 'alphabetize_by_last_name' );

// To reflect the alphabetical sorting of the member directory, you
// could also format the names to show the last name first. Here is
// a helper function to format names as follows: Last, First Middle
// Etc.
//
// To use this function every time a user's name is shown or queried,
// simply add it as a filter:
//
// `add_filter ('bp_get_member_name', 'format_last_name_first' );`
//
// To only reformat the name in the member directory, change your
// members/members-loop.php file in your (child)theme. Look for
// `bp_member_name()`
// and replace it with
// `echo format_last_name_first ( bp_get_member_name() );`

/**
 * Helper function for formatting a name: Last, First Middle Etc.
 *
 * @param string $name
 * @return string Formatted name
 */
function format_last_name_first( $name ) {
    if ( $first_space = strrpos( $name, " ") )
        $name = substr( $name, $first_space + 1 ) . ", " . substr( $name, 0, $first_space );
    return $name;
}

// BONUS: To make alphabetical sorting the default sorting, use the
// function below. 
//
// In order for this to work properly, `<option value="alphabetical">`
// must be the first option for the members-order-select in
// members/index.php.

function sort_members_alphabetically( $qs = '', $object = false ) {
    if( $object != 'members' ) //for members only
        return $qs;

    if ( empty( $qs ) || ! strpos( $qs, "type=" ) ) {
        $args = wp_parse_args($qs);
        $args['type'] = 'alphabetical';
        $args['action'] = 'alphabetical';

        $qs = build_query( $args );
    }

    return $qs;
}
add_action( 'bp_ajax_querystring', 'sort_members_alphabetically', 11, 2 );


/**
 * Select Alphabet on Select Box.
 * https://gist.github.com/KaineLabs/4795fa7a6725389b246c9b4020491798#file-yzc_make_alphabet_selected-php
 */
function yzc_make_alphabet_selected() {

    ?>
    <script type="text/javascript">

    ( function( $ ) {

    $( document ).ready( function() {
    
        jQuery( '#members-order-by option[value="alphabetical"], #groups-order-by option[value="alphabetical"]' ).attr( 'selected', true ).trigger( 'change');

    });

    })( jQuery );
    </script>
    <?php

}
add_action( 'wp_footer', 'yzc_make_alphabet_selected' );

/**
 * Members Directory - Set Default Filter.
 */
function yzc_set_default_members_directory_filter( $loop ) {

    if ( bp_is_members_directory() && ! isset( $_POST['filter'] ) ) {
        $loop['type'] = 'alphabetical';
    }

    return $loop;

}

add_filter( 'bp_after_has_members_parse_args', 'yzc_set_default_members_directory_filter', 9999 );

/**
 * Members Directory - Set Default Filter.
 */
function yzc_set_default_groups_directory_filter( $loop ) {

    if ( bp_is_groups_directory() && ! isset( $_POST['filter'] ) ) {
        $loop['type'] = 'alphabetical';
    }

    return $loop;

}

add_filter( 'bp_after_has_groups_parse_args', 'yzc_set_default_groups_directory_filter', 9999 );